"""Remediate copyright-liability chunks in upsc_chunks.

Targets chunks whose source is IGNOU / NIOS / eGyanKosh course material
(MPY, MPYE, BPAC, BPCS, MPA013, EPA, NIOS). For each such chunk, replace the
stored verbatim text with ORIGINAL, fact-dense, own-words knowledge points
generated by Gemini, so no raw copyrighted text remains stored or served.
Facts, names, dates, definitions are preserved in substance; wording is new.

  - chunk            := new own-words knowledge points (replaces raw text)
  - search_vector    := recomputed tsvector of new text
  - embedding        := recomputed (best-effort; retried/resumed if quota)
  - chunk_version    := bumped (text)
  - source_file      := unchanged (provenance retained for audit)

Resumable + quota-tolerant: done chunks recorded in `chunk_remediation`
(chunk_id TEXT PK). Safe to re-run repeatedly; quiesces on exhausted quota.
"""
import os, time
from concurrent.futures import ThreadPoolExecutor, as_completed
import requests

GEN_MODEL = os.getenv("RMD_GEN_MODEL", "gemini-3.6-flash")
EMBED_MODEL = os.getenv("RMD_EMBED_MODEL", "gemini-embedding-2")
DIM = int(os.getenv("RMD_EMBED_DIM", "3072"))
KEY = os.getenv("GEMINI_API_KEY", "")
GEN_N = int(os.getenv("RMD_GEN_CONCURRENCY", "3"))
EMB_N = int(os.getenv("RMD_EMBED_CONCURRENCY", "3"))
BATCH = int(os.getenv("RMD_BATCH", "1000"))
DRY = os.getenv("RMD_DRY_RUN", "0") == "1"
RMD_429_GEN_TRIES = int(os.getenv("RMD_429_GEN_TRIES", "6"))
RMD_429_EMB_TRIES = int(os.getenv("RMD_429_EMB_TRIES", "8"))

GEN_URL = f"https://generativelanguage.googleapis.com/v1beta/models/{GEN_MODEL}:generateContent?key={KEY}"
EMBED_URL = f"https://generativelanguage.googleapis.com/v1beta/models/{EMBED_MODEL}:embedContent?key={KEY}"
gen_s = requests.Session()
emb_s = requests.Session()

RISKY_RE = r"(MPY|MPYE|BPAC|BPCS|MPA013|MPA-013|EPA-|NIOS|IGNOU|eGyanKosh)"

PROMPT = (
    "You are a content-remediation pipeline for a UPSC (GS) study app. "
    "Rewrite the given study text as ORIGINAL, fact-dense bullet knowledge points. "
    "STRICT RULES:\n"
    "- Express EVERY fact in YOUR OWN WORDS. Do NOT reproduce any sentence, clause, "
    "phrase, or contiguous run of the source verbatim.\n"
    "- Never copy tables cell-for-cell, blockquoted definitions, direct quotes, or "
    "any diagram text. Restate them entirely in your own words.\n"
    "- Preserve every fact, name, date, number, definition, concept, thinker and "
    "example in substance. Do NOT add outside information.\n"
    "- Keep it a faithful study summary of THIS text only; do not generalise beyond it.\n"
    "- Output only the paraphrased bullets (no preamble, no 'Here is...')."
)

def get_conn():
    import psycopg2
    return psycopg2.connect(
        host=os.getenv("PG_HOST", "postgres"),
        dbname=os.getenv("PG_DB", "aryabhata_db"),
        user=os.getenv("PG_USER", "aryabhata_user"),
        password=os.getenv("PG_PASS", "Password123"))

def ensure_tables(conn):
    with conn.cursor() as cur:
        cur.execute("""
            CREATE TABLE IF NOT EXISTS chunk_remediation (
                chunk_id TEXT PRIMARY KEY,
                remediated_at TIMESTAMP DEFAULT NOW()
            )
        """)
    conn.commit()

def get_todo():
    conn = get_conn()
    try:
        with conn.cursor() as cur:
            cur.execute("""
                SELECT c.id, c.chunk
                FROM upsc_chunks c
                LEFT JOIN chunk_remediation r ON r.chunk_id = c.id
                WHERE c.source_file ~ %s AND r.chunk_id IS NULL
                ORDER BY c.id
                LIMIT %s
            """, (RISKY_RE, BATCH))
            return cur.fetchall()
    finally:
        conn.close()

def pending_total():
    conn = get_conn()
    try:
        with conn.cursor() as cur:
            cur.execute("""
                SELECT COUNT(*) FROM upsc_chunks c
                LEFT JOIN chunk_remediation r ON r.chunk_id = c.id
                WHERE c.source_file ~ %s AND r.chunk_id IS NULL
            """, (RISKY_RE,))
            return cur.fetchone()[0]
    finally:
        conn.close()

def gen_abs(text):
    payload = {"contents": [{"parts": [{"text": PROMPT + "\n\nTEXT:\n" + text}]}],
               "generationConfig": {"temperature": 0.3, "maxOutputTokens": 2048}}
    for attempt in range(RMD_429_GEN_TRIES):
        try:
            r = gen_s.post(GEN_URL, json=payload, timeout=120)
            if r.status_code == 429:
                if attempt < RMD_429_GEN_TRIES - 1:
                    time.sleep((2 ** attempt) * 2)
                    continue
                return ("QUOTA", None)
            r.raise_for_status()
            out = (r.json().get("candidates") or [{}])[0].get("content", {}).get("parts", [{}])[0].get("text", "")
            return ("OK", out.strip()) if out and out.strip() else ("EMPTY", None)
        except Exception as e:
            if "429" in str(e):
                return ("QUOTA", None)
            if attempt == 5:
                return ("ERR", None)
            time.sleep(2 ** attempt)
    return ("ERR", None)

def embed(text):
    body = {"model": f"models/{EMBED_MODEL}", "content": {"parts": [{"text": text}]},
            "taskType": "RETRIEVAL_DOCUMENT", "outputDimensionality": DIM}
    for attempt in range(RMD_429_EMB_TRIES):
        try:
            r = emb_s.post(EMBED_URL, json=body, timeout=60)
            if r.status_code == 429:
                if attempt < RMD_429_EMB_TRIES - 1:
                    time.sleep((2 ** attempt) * 2)
                    continue
                return ("QUOTA", None)
            r.raise_for_status()
            return ("OK", r.json()["embedding"]["values"])
        except Exception as e:
            if "429" in str(e):
                return ("QUOTA", None)
            if attempt == 5:
                return ("ERR", None)
            time.sleep(2 ** attempt)
    return ("ERR", None)

def write(cid, new_text, vec):
    conn = get_conn()
    try:
        with conn.cursor() as cur:
            cur.execute(
                "UPDATE upsc_chunks SET chunk=%s, search_vector=to_tsvector('english', %s), "
                "chunk_version=coalesce(chunk_version, 0) + 1, embedding=NULL::halfvec WHERE id=%s",
                (new_text, new_text, cid))
            if vec:
                vals = "[" + ",".join(str(float(v)) for v in vec) + "]"
                cur.execute("UPDATE upsc_chunks SET embedding=%s::halfvec WHERE id=%s", (vals, cid))
            cur.execute("INSERT INTO chunk_remediation (chunk_id) VALUES (%s) ON CONFLICT DO NOTHING", (cid,))
        conn.commit()
    finally:
        conn.close()

def main():
    ensure_tables(get_conn())
    t0 = time.time()
    tot_done = 0
    while True:
        todo = get_todo()
        if not todo:
            print(f"[{round((time.time()-t0)/60,1)}m] no pending risky chunks; exiting", flush=True)
            return
        gen_ok, emb_ok = {}, {}
        qu = er = 0
        with ThreadPoolExecutor(max_workers=GEN_N) as ex:
            fs = {ex.submit(gen_abs, c): cid for cid, c in todo}
            n = 0
            for fut in as_completed(fs):
                cid = fs[fut]
                st, out = fut.result()
                n += 1
                if st == "OK":
                    gen_ok[cid] = out
                elif st == "QUOTA":
                    qu += 1
                else:
                    er += 1
                if n % 25 == 0:
                    print(f"[{round((time.time()-t0)/60,1)}m] gen {n}/{len(todo)} ok={len(gen_ok)} err={er} quota={qu}", flush=True)
        print(f"[{round((time.time()-t0)/60,1)}m] gen round ok={len(gen_ok)} err={er} quota={qu}", flush=True)

        with ThreadPoolExecutor(max_workers=EMB_N) as ex:
            fs = {ex.submit(embed, gen_ok[c]): c for c in gen_ok}
            for fut in as_completed(fs):
                cid = fs[fut]
                st, vec = fut.result()
                if st == "OK" and vec:
                    emb_ok[cid] = vec
        print(f"[{round((time.time()-t0)/60,1)}m] embed round ok={len(emb_ok)}", flush=True)

        if DRY:
            for cid, t in gen_ok.items():
                print(f"    {cid[:20]}: {t[:120].replace(chr(10),' ')}...", flush=True)
            print("=== DRY RUN: stopping without writes ===", flush=True)
            return

        for cid, t in gen_ok.items():
            write(cid, t, emb_ok.get(cid))
        tot_done += len(gen_ok)
        print(f"[{round((time.time()-t0)/60,1)}m] remediated={tot_done} pending_left={pending_total()}", flush=True)

        if gen_ok:
            time.sleep(2)
        elif qu:
            print("=== generation quota exhausted; sleeping 300s ===", flush=True)
            for _ in range(60):
                time.sleep(5)

if __name__ == "__main__":
    main()
